import type { Metadata } from 'next';
import '@/lib/styles/globals.css';
import { fontMono, fontSans } from '@/lib/styles/fonts';
import Layout from '@/lib/components/layout';
import ReactQueryProvider from '@/providers/reactQueryProvider';
import { Button } from '@/lib/components/ui/button';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  metadataBase: new URL('https://reading-list-iota.vercel.app/'),
  authors: [
    { name: 'Naufaldi', url: 'https://www.linkedin.com/in/naufaldirafif/' },
  ],
  keywords: ['reading-list', 'book', 'dashboard', 'nextjs'],
  openGraph: {
    title: 'Reading List Dashboard',
    description: 'official tutorial nextjs dashboard',
    url: 'https://reading-list-iota.vercel.app/',
    type: 'website',
  },
  twitter: {
    site: '@reading-list',
    description: 'reading list tutorial',
    title: 'Reading List Apps',
    creator: '@f2aldi',
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${fontSans.variable} ${fontMono.variable}`}>
        {/* <button onClick={() => addComment('error')}> on Error Trigger </button> */}
        <ReactQueryProvider>
          <Layout>{children}</Layout>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
